train:
  get_spectrogram: # special key for getting spectrogram
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
    n_fft: 400
    hop_length: 160
    n_mels: 80
  spectrogram:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.spec_augs.Logarithm
  # audio: # name of the tensor on which we apply transform
  #   _target_: torchvision.transforms.v2.Compose
  #   transforms:
  #     - _target_: src.transforms.wav_augs.Gain
        
inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
    n_fft: 400
    hop_length: 160
    n_mels: 80
  spectrogram:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.spec_augs.Logarithm
